#! /usr/bin/python

import os

version = 0.12int

origin = "https://github.com/Aidr0ne/engine"
name = "engine"

tools_origin = "https://github.com/Aidr0ne/tools"

print("------------")
print(f"Setup V:{version}")
print("------------")

print("What kind of project do you wish to setup")
print("1. General Project")

i = int(input(": "))
if i == 1:
    get = "General"

print("What name would you like the engine to have")
print("This will affect how you import it eg import thing.show")
print("Leave blank for the default")

i = input(": ")
if i == "": nm = "engine"
else: nm = i

build_tool = input("Would you like the build tool (y/n): ")
editor = input("Would you like the editor tool (y/n): ")

os.system(f"git clone {origin}")
os.system(f"mv {name}/{get} {nm}")
os.system(f"rm -rf {name}")

os.system(f"git clone {tools_origin}")

if build_tool == "y":
    os.system(f"mv tools/build.py build.py")

if editor == "y":
    os.system(f"mv tools/editor.py editor.py")

os.system(f"rm -rf tools")

to_add = f"name={nm}"

os.system(f"echo {to_add} >> {nm}/config.py")
