#! /usr/bin/python

import os
import sys

version = 0.12

origin = "https://github.com/Aidr0ne/engine"
name = "engine"

tools_origin = "https://github.com/Aidr0ne/tools"

print("------------")
print(f"Setup V:{version}")
print("------------")

print("In order to use the Engine you must agree to the License (GNU GPLv3)")
print("Key summary:")
print("You may Modify, Distribute and use this software for commercial and private use")
print("A copy of this license must be included with any distribution of this software")
print("Your software must be open source (Eg: publish the full source code on github gitlab etc)")
print("The source code must be available if distributed in any form")
i = input("Do you Agree (y/n): ")
if i == "n":
    print("Bye then...")
    sys.exit(0)

print("What kind of project do you wish to setup")
print("1. General Project")

i = int(input(": "))
if i == 1:
    get = "General"

print("What name would you like the engine to have")
print("This will affect how you import it eg import thing.show")
print("Leave blank for the default")

i = input(": ")
if i == "": nm = "engine"
else: nm = i

build_tool = input("Would you like the build tool (y/n): ")
editor = input("Would you like the editor tool (y/n): ")

os.system(f"git clone {origin}")
os.system(f"mv {name}/{get} {nm}")
os.system(f"mv {name}/LICENSE {nm}/LICENSE")
os.system(f"rm -rf {name}")

os.system(f"git clone {tools_origin}")

if build_tool == "y":
    os.system(f"mv tools/build.py build.py")

if editor == "y":
    os.system(f"mv tools/editor.py editor.py")

os.system(f"rm -rf tools")

to_add = f"name={nm}"

os.system(f"echo {to_add} >> {nm}/config.py")
